### ISSUE TITLE
Problem with New scp spec. for single sided disks

### ISSUE THREAD

**Issue by ILAHWWINC** [davidgiven/fluxengine#168]
Fluxengine reports „scp file corrupt“ when trying to convert a scp file (C64 - single side) dumped with Greaseweazle 0.18.
This will be the result of new spec. / format of scp dumps for single sided disks.

**Comment by ILAHWWINC** [comment]
The same problem occurs on .scp files converted from .d64 to .scp with hxc-beta export function.

**Comment by davidgiven** [comment]
Sorry for the delay, immersed in another project... fabulous. I think I may have actually caused the new spec by talking about problems with the old one to the author. Can you attach a sample, please? Thanks!

**Comment by ILAHWWINC** [comment]
[mydisk-scp.zip](https://github.com/davidgiven/fluxengine/files/4837999/mydisk-scp.zip)

Here are two dumps of the Commodore 1541 Test-Demo-Disk. They are single-sided, one with single-step (80 Tracks) the other with double-step (40 Track) option.

**Comment by davidgiven** [comment]
Thanks --- I'll take a look.

**Comment by davidgiven** [comment]
This should now be working --- I can convert your files fine (in both directions). The new code is in the scp branch if you want to try it.

**Comment by ILAHWWINC** [comment]
Release 418 still shows same problem. Will the change be in a futher release?

**Comment by davidgiven** [comment]
It's not merged yet. Can you test the version from the branch, or can you not build the client yourself?

**Comment by ILAHWWINC** [comment]
No i can not build it on my own.

**Comment by davidgiven** [comment]
No problem --- I've merged the change, so the latest release (at least, in a few minutes after this message) should contain the fix.

**Comment by ILAHWWINC** [comment]
Works fine. Thank you for your work and the response to my problem.

**Comment by davidgiven** [comment]
No problem --- thanks for the bug report!
