### ISSUE TITLE
PSoC is constantly connection/disconnection [Win7]

### ISSUE THREAD

**Issue by PoP-SE** [davidgiven/fluxengine#60]
I build the firmware (in debug mode) it programmed without any problems. 

When connection the USB-micro side, it's starting to connect and disconnect continuously. 

I'm new to this and not sure what else you need. Let me know.

**Comment by davidgiven** [comment]
There is an outstanding issue where the board doesn't work if plugged into a low-power socket --- I have just fixed this, so could you try updating from git and rebuilding/reflashing the firmware and letting me know if it works?

**Comment by PoP-SE** [comment]
I rebuild and reprogrammed the firmeware but I still have the connecting/disconnecting issue.

**Comment by davidgiven** [comment]
Curses. Are you Windows or Linux? If Linux, could you plug the device in, do `sudo dmesg | tail -100` and copy me the result?

**Comment by PoP-SE** [comment]
Sorry, I'm on windows 7.

**Comment by davidgiven** [comment]
Okay, so on Windows 7 I think you can use UsbLogView to get the same information: http://www.nirsoft.net/utils/usb_log_view.html What I'm looking for is any indication of why the device is disconnecting --- whether Windows is cutting it off or whether it's disconnecting of its own accord.

I'm afraid that other than that I'm mostly out of ideas --- not only does my board doesn't do this, but when I tried investigating the continuously-restarting-in-release-mode thing that doesn't seem to be happening any more. Without access to the device I can't really debug it.

Other than the obvious simple diagnostic suggestions (have you tried a different USB port? A different computer? Does working through the Blinky PSoC tutorial work? etc) I don't have any easy answers here, and it'll probably require investigation at your end if you have the expertise. The PSoC debugger will work fine, allowing you to single-step through code, provided you don't actually try to access disks with the debugger running (the debugger shares some pins with the FDD).

It may also be worth trying to disable the watchdog timer by commenting out the line to `CyWdtStart()` in `main()` in the firmware.

**Comment by PoP-SE** [comment]
I just tried the nirsoft usb-log-viewer but the psoc isn't showing up. I tried all usb ports at this pc without any luck. I also tried another pc, this time it's working. So I guess it has something to do with my laptop, not sure. I also have no experience with debugging this. If you like we can try a teamviewer session if you'd like to take a look.

**Comment by PoP-SE** [comment]
Oh, I also removed the CyWdtStart() from main and now it's not disconnection any more, but it's not connecting anymore and the client can't find it (it also didn't while the device was always connection / disconnecting).

**Comment by davidgiven** [comment]
That's interesting; it sounds like the PC is never configuring the device. The only reason I can think of is that it doesn't think there's enough power, but I fixed that bug... are you sure you updated from github before recompiling? If that fails, try with a powered hub?

Sadly, I have no idea what else to try. I only know just enough Windows to develop with, and don't know enough to debug it remotely; sorry. If you ever try Linux on that machine, I'd be interested to see the logs, though. But unless I can duplicate the problem elsewhere I don't think there's anything I can do. Given that it works everywhere else it does sound like there's something weird about that machine.

**Comment by PoP-SE** [comment]
I'm sure I used your updated code. I also tried an USB-Hub, but it was not a powerd one. So no luck there, I'm looking wo a powerd one. I'll keep you updated.

Thank you for your time. I'm sure it has something to do with my laptop.

**Comment by davidgiven** [comment]
Belatedly, good to know. Closing bug for cleanup.
