### ISSUE TITLE
Unused & undocumented dependency on absl

### ISSUE THREAD

**Issue by VorpalBlade** [davidgiven/fluxengine#842]
1. https://github.com/davidgiven/fluxengine/blob/master/doc/building-client.md (the Ubuntu section) does not list absl as a dependency.
2. Using the `namcap` Arch Linux packaging linting tool lists that fluxengine links but doesn't use a lot of absl libraries.

```
fluxengine-git W: Unused shared library '/usr/lib/libabsl_die_if_null.so.2508.0.0' by file ('usr/bin/brother120tool')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_log_internal_conditions.so.2508.0.0' by file ('usr/bin/brother120tool')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_examine_stack.so.2508.0.0' by file ('usr/bin/brother120tool')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_log_internal_format.so.2508.0.0' by file ('usr/bin/brother120tool')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_log_internal_structured_proto.so.2508.0.0' by file ('usr/bin/brother120tool')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_log_internal_log_sink_set.so.2508.0.0' by file ('usr/bin/brother120tool')
[... really long output, hundreds of lines ...]
fluxengine-git W: Unused shared library '/usr/lib/libabsl_strings.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_strings_internal.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_string_view.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_int128.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_base.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_spinlock_wait.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_throw_delegate.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_raw_logging_internal.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
fluxengine-git W: Unused shared library '/usr/lib/libabsl_log_severity.so.2508.0.0' by file ('usr/bin/upgrade-flux-file')
```

So *most* parts of absl are linked pointlessly.

**Comment by davidgiven** [comment]
abseil is a transitive dependency from protobuf, which is why it's not listed. But by the same token, it's not linked to directly, either, which puzzles me as to why you're getting warnings:

```
$ ldd brother120tool 
	linux-vdso.so.1 (0x00007f4fe37f2000)
	libfmt.so.11 => /lib64/libfmt.so.11 (0x00007f4fe379c000)
	libprotobuf.so.30 => /lib64/libprotobuf.so.30 (0x00007f4fe3400000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f4fe3752000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f4fe372a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4fe3000000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4fe330b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4fe32df000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4fe2e0d000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f4fe371c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4fe37f4000)
```

Could this be caused by some of arch's distro-specific compilation flags?

**Comment by VorpalBlade** [comment]
> Could this be caused by some of arch's distro-specific compilation flags?

Hm, I don't really see any that would be relevant:

```bash
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
         -Wl,-z,pack-relative-relocs"
```

If `--add-needed` had been there, perhaps. But `--as-needed` should do the *opposite*.

But this seems potentially relevant (if you use pkg-config, I haven't checked):

```console
❯ cat /usr/lib/pkgconfig/protobuf.pc       
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: Protocol Buffers
Description: Google's Data Interchange Format
Version: 33.1.0
Requires: absl_absl_check absl_absl_log absl_algorithm absl_base absl_bind_front absl_bits absl_btree absl_cleanup absl_cord absl_core_headers absl_debugging absl_die_if_null absl_dynamic_annotations absl_flags absl_flat_hash_map absl_flat_hash_set absl_function_ref absl_hash absl_layout absl_log_initialize absl_log_globals absl_log_severity absl_memory absl_node_hash_map absl_node_hash_set absl_random_distributions absl_random_random absl_span absl_status absl_statusor absl_strings absl_synchronization absl_time absl_type_traits absl_utility utf8_range
Libs: -L${libdir} -lprotobuf 
Cflags: -I${includedir} -DPROTOBUF_USE_DLLS
Conflicts: protobuf-lite
```

**Comment by davidgiven** [comment]
Looks like I'm using a different .pc file for protobuf, as well:

```
$ cat /usr/lib64/pkgconfig/protobuf.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: Protocol Buffers
Description: Google's Data Interchange Format
Version: 3.19.6
Libs: -L${libdir} -lprotobuf
Libs.private: -lz 

Cflags: -I${includedir}
Conflicts: protobuf-lite
```

**Comment by davidgiven** [comment]
Oh, yes, they added the Abseil dependency somewhere around 20, IIRC. That'll be it.

I fixed the LDFLAGS/CFLAGS issue, so give it another try with --as-needed?

**Comment by VorpalBlade** [comment]
#845 didn't actually solve this, seems --as-needed isn't it. I will have to do some further research in the coming days.

**Comment by davidgiven** [comment]
Aha --- there's a --no-as-needed added in the Makefile. I think this is there to ensure the pthreads library gets added, which seems like it was necessary on Debian 11. https://github.com/davidgiven/fluxengine/commit/149e5c6fba19d07552bdd4b2d85b33f932f68902

**Comment by davidgiven** [comment]
I've given up on Debian 11 as there's no C++23 support, so there's now also no `--no-as-needed` any more. I'm going to tentatively mark this as fixed --- feel free to reopen if that's not true.
